### ISSUE TITLE
Backwards compatibility for webp images.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-main-2022#112]
I ran into this, while testing #111. If we are going to fix the layout for containers, we should probably do the same for these images that are rendering as broken images.

> The only concern I can see there being is if we need back-compat support for non-webp-enabled browsers. That's a followup issue if it is determined to be a problem after launch though IMHO.

_Originally posted by @dd32 in https://github.com/WordPress/wporg-main-2022/issues/42#issuecomment-1208864423_

**Comment by ryelle** [comment]
What browser were you using that they're broken? According to caniuse, [webp is pretty broadly supported](https://caniuse.com/?search=webp) except for IE11 — and I don't think we need to support IE.

**Comment by StevenDufresne** [comment]
macOs: Catalina
Browser: Safari 13.1

Via BrowserStack

**Comment by ryelle** [comment]
Do we have any statistics that say we need to support back to Safari 13? 

My hesitation is that I don't know if there is a core/editor-supported way to provide fallbacks, so would we need to stop using `webp` entirely? The file size savings from webp were impressive, so it would be nice to keep that if we can.

**Comment by StevenDufresne** [comment]
A quick look at analytics reveals:

0.6% of users are using Safari 13.X. That number inches slightly higher if we account for lesser versions. While 0.6% may feel small, it does account for a significant number of real people.

**Comment by StevenDufresne** [comment]
I don't know if we need to necessarily serve a fallback image, but it should probably not look broken.

**Comment by ryelle** [comment]
For reference, some images work and some don't (~not totally sure why, since that showcase image is theoretically a webp~ despite being `.webp`, when returned via `https://i2.wp.com/wordpress.org/files/2022/08/Showcase_2560.webp?w=2560&ssl=1` it's `content-type: image/png`).

Anyway, to get this to "readable," we need to add a background to the editor section. The missing community image is awkward but not critical to understanding the page.

_screenshot from browserstack_

![](https://user-images.githubusercontent.com/541093/188474845-28b4eeba-c54e-49bf-a60b-5b356fc56997.png)
