### ISSUE TITLE
Preload required font subsets for rosetta sites once we support them

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-main-2022#136]
See https://github.com/WordPress/wporg-main-2022/pull/103/commits/93a44fa9155caad28bc76e46a565cedd6c24bfc6#diff-b4f8b812eb373b4d5dd73ee10679133902227145fb8666a0d87cb282ed5bb51eR67

Currently, we specifically specify the preloaded font subsets as `Latin` for [wporg-main homepage heading](https://github.com/WordPress/wporg-main-2022/pull/103/commits/7696aa3b573a4e0901ac0898f5b4da45e0f36fe0). In the future, we also want to preload the required fonts for the rosetta sites once they are supported.

**Comment by ryelle** [comment]
@dd32 [suggested](https://github.com/WordPress/wporg-mu-plugins/pull/247#issuecomment-1232425717) adding a translation string so that translators can set the correct subset. There's some prior art with this concept in some older core themes, like [Twenty Seventeen](https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentyseventeen/functions.php#L292) which lets translators disable Libre Franklin if it doesn't support the right character set.

I'm thinking something like this…

```php
/*
 * translators: Subsets can be any of cyrillic, cyrillic-ext, greek, greek-ext, vietnamese, latin, latin-ext.
 */
$subsets = _x( 'latin', 'Character subsets, comma separated', 'wporg' );
```

Which the Vietnamese translator could translate to `latin, latin-ext, vietnamese`, and then we'd preload all those variants. 

We might want to default to always preloading Latin? Spot-checking a few non-latin Rosetta sites there's always a little latin text.

Also, these fonts are already in use in the global header & footer, including on Rosetta sites, so even though we haven't pushed the new site design out, preloading these fonts would still help.

**Comment by outdoor2kode** [comment]
> I'm thinking something like this… /* * translators: Subsets can be any of cyrillic, cyrillic-ext, greek, greek-ext, vietnamese, latin, latin-ext. */ $subsets = _x( 'latin', 'Character subsets, comma separated', 'wporg' );

I'll try it at https://github.com/WordPress/wporg-mu-plugins/issues/293 and I might default preloading Latin in mu-plugins as well, probably just preload it inside the function where it's preloaded currently, which is `render_global_header`, since global header seems to exist in every subsite.
