### ISSUE TITLE
Update the alignment of the counter page to the center

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-main-2022#137]
When we worked on the design for the Counter page we didn't realize that the counter gets reset on main releases. To make sure the page always looks good we'd like to change the alignment of the title and the number, so it's center-aligned:

![image](https://user-images.githubusercontent.com/4933/197014804-ebd0968e-e903-425e-b1a9-27c74c574317.png)

I tried to do it myself, but I wasn't able to update the alignment of the number in the editor.

**Comment by ryelle** [comment]
This has been fixed in https://github.com/WordPress/wporg-main-2022/commit/6b881368d36481d473f55cfcbc3a42aad53573d0 & https://github.com/WordPress/wporg-main-2022/commit/8a419cee6694fe5d704c0b5b4af9b812b241b7b9, I just haven't had time to deploy them yet. I will be able to later today, and I'll comment back here when it's live.

**Comment by ryelle** [comment]
and it's deployed 🙂  — https://wordpress.org/download/counter/

**Comment by javierarce** [comment]
120M thanks!
