### ISSUE TITLE
How do we handle translation?

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-main-2022#15]
In the context of the front page and download pages:

* How does this relate to Rosetta?
* Which parts of those pages (if any) need to be translated via GlotPress?
* Is there content that should be translated outside GlotPress (eg by separate pages on Rosetta sites)?
* What translation mechanisms are we using in code? (see https://github.com/WordPress/wporg-main-2022/issues/1#issuecomment-1190589110)
* What other decisions do we need to make about translation?

Given the condensed time frame, we probably need a simple option that's easy, and a good option that's a post-launch v2.

**Comment by dd32** [comment]
> How does this relate to Rosetta?

In an ideal world, we'd launch this for both en_US (wordpress.org/) and for all locales (xx.wordpress.org/) at the same time. However, we've got no existing successful deployments where we're translating a Block-Editor-built page, other than minimal proof-of-concepts.

> Which parts of those pages (if any) need to be translated via GlotPress?

IMHO, all visible text on the page should be translated via GlotPress. There are alternatives which might make sense in the future (Gutenberg multilingual support for example), but currently GlotPress is the defacto option here that I don't see the need to challenge.

> Is there content that should be translated outside GlotPress (eg by separate pages on Rosetta sites)?

I don't think so - however, there are some data points that might differ between English US and localised sites - For example, a locale that isn't active and their last release was an older version.  That's worth another discussion around how to handle those situations though, as we don't really want that scenario to exist.

> What translation mechanisms are we using in code?

I don't think we should do anything "special" here - just using regular `__()`/`_e()` where appropriate within any code, and using a plugin that can dynamically translate `post_content` and the other site content entered via the WordPress editor. 

That goes back to my previous mention that we don't have anything that currently works like that in production, although we have variants of it (Theme/Plugin description translations, Translated Patterns, etc) and some work that was only in concept-state for `/gutenberg/` translation.

> Given the condensed time frame, we probably need a simple option that's easy,

Whilst in an ideal world, we'd launch rosetta at the same time as the main site, realistically given the accelerated timelines in play, I feel it's safer to work with the assumption that Rosetta sites will not immediately get the new theme.
That will also ensure no rosetta/translation-related issues delay launch or any post-release issues that crop up. 

That would likely mean we'd have a rosetta-release-day as a follow-up task and enabled for an active locale (or two) for testing and as the localisation teams complete the translation for the new strings. 
That would remove the potential issues of releasing it with a bunch of locales without fully translated homepages, which when they're currently translated, wouldn't be the best example of success.

**Comment by dd32** [comment]
> That would likely mean we'd have a rosetta-release-day as a follow-up task

The remaining question here however is the timeline for when that is, I'm personally not too sure what the timeline we should be aiming for here is. It depends on how soon we should expect an upstream-Gutenberg-native-translation option to be available, and/or when we have a more-than-proof-of-concept post translation plugin available.

I think it's fair to say, for expectation purposes for others, it should not be assumed that this will be available at the time of general launch of the theme, nor within the following few weeks, and that the timeline is more likely to be months (or perhaps sooner, if a proof-of-concept implementation is determined to be stable and performant enough for production use).

**Comment by tobifjellner** [comment]
Simple option: Some way to see the diff between current version of a page and some previous version, so that a translator can know what has changed and update the localized version accordingly.

**Comment by tellyworth** [comment]
If we're translating everything via GlotPress, that essentially means that Rosetta as it currently exists is being made redundant, right? It would still exist for pages handled by the old theme, but the new pages wouldn't exist separately as independent posts on Rosetta sites?

What would the mechanism look like for handling that in Rosetta? Some code that says "if this is a block theme page, switch_to_blog( main_site ) and display that with Glotpress translation"?

Would we also need some Rosetta code to prevent the creation of pages that are handled on the main site, and/or make it clear how to edit that (perhaps redirect edit buttons to the main site?)

**Comment by tellyworth** [comment]
> That goes back to my previous mention that we don't have anything that currently works like that in production, although we have variants of it (Theme/Plugin description translations, Translated Patterns, etc) and some work that was only in concept-state for /gutenberg/ translation.

Would it make sense to get that WIP code into a repo as a plugin, and set up some unit tests so we can work out the bugs?

**Comment by dd32** [comment]
> tobifjellner: Some way to see the diff between current version of a page and some previous version, so that a translator can know what has changed and update the localized version accordingly.

Requiring manual edits to pages in order to keep them in sync is not ideal at all, and not something I want to encourage at all on WordPress.org. In the past, too many pages would remain stale for years causing outdated information to be in search engine indexes. Due to WordPress.org using `hreflang` tags now, rosetta pages are returned in searches in preference to the en_US homepage, so we don't really want to have a situation where some locale that hasn't been updated in years lists WordPress 3.5 as the latest stable release again.

I recognise that this approach is being used for some things at present, HelpHub for example, but I would not consider those to be an ideal translation experience. _(EDIT: An ideal translation experience, from the point of view of keeping all locales updated and with accurate information. For support documentation, it might be enough, but for the homepage/download pages, I don't think it's "enough".)_


> tellyworth: If we're translating everything via GlotPress, that essentially means that Rosetta as it currently exists is being made redundant, right? It would still exist for pages handled by the old theme, but the new pages wouldn't exist separately as independent posts on Rosetta sites?

The way Rosetta works today, is that we create the pages (`/`, `/downloads`, `/about/`, etc) on the Rosetta site and have the template set to that of the theme. The theme template uses `__()` and `_e()` for all strings. The pages are owned by the `wordpressdotorg` user and there's code on Rosetta to deny any edits to pages owned by that user.

Translating a Block-editor built page would be very similar in my mind, except that instead of pulling from the `.php` template with `__()` we'd be pulling from the `post_content` and one of our functions that pulls translations directly from GlotPress.

**Comment by dd32** [comment]
> tellyworth: Would it make sense to get that WIP code into a repo as a plugin, and set up some unit tests so we can work out the bugs?

I'll try to get a PR up on WordPress/wordpress.org with some of the code I have locally today.

**Comment by dd32** [comment]
The draft PR is up here: https://github.com/WordPress/wordpress.org/pull/90

After throwing a bunch of code at it, this is in a much better state than I anticipated. I still believe we should target rosetta roll out for after the en_US launch though.

**Comment by tellyworth** [comment]
> The draft PR is up here: https://github.com/WordPress/wordpress.org/pull/90

Nice! Let's see if we can loop in Team Orbit to help with that one - cc @akirk.

**Comment by dd32** [comment]
As mentioned [here](https://make.wordpress.org/design/2022/07/27/project-update-wordpress-org-homepage-and-download-page-mockups/#comment-26547) by @tobifjellner:
> and the layout will need to work also for RTL languages (those that are written from right-to-left)

I'm not sure how this will work for RTL, flipping the design, can the re-arrangements for RTL be done purely through CSS? or are we going to end up with a situation where we need to re-order column blocks?

**Comment by akirk** [comment]
> I'm not sure how this will work for RTL, flipping the design, can the re-arrangements for RTL be done purely through CSS? or are we going to end up with a situation where we need to re-order column blocks?

While not ideal, I could see us using custom transforms before rendering for RTL languages (i.e. `preg_replace()` per page and language).

**Comment by dd32** [comment]
> While not ideal, I could see us using custom transforms [...]

If absolutely required, yeah, that's an option we'd have. I'm hopeful that we'd be able to resolve it using CSS though.

The main reason I say that I hope CSS will do it, is that we'll need to support non-developers updating copy (and potentially design) through the Block Editor - Those changes won't necessarily be made with translations, let alone RTL translations, in mind. Using code-level transformations could potentially ultimately limit editing to pure copy and not adding/removing blocks/etc.. As far as I know, we're not going to be locking the block structure within the editor down at all.

**Comment by ryelle** [comment]
#118 updates the pattern templates with translation functions, so that content can be translated now. https://github.com/WordPress/wporg-parent-2021/commit/732ae1bb901ec81e163d62bbb95b95cf7b8db30c adds the RTL CSS to the parent theme, so the base styles are taken care of (https://github.com/WordPress/wporg-mu-plugins/issues/269 is open to remove duplication of the parser code, and integrate any changes from https://github.com/WordPress/wordpress.org/pull/90). 

There are a few places that use inline styles/alignment classes, so we need a solution here (`preg_replace` on the `render_block_core/pattern` hook?), tracking that in #123.

This theme also needs to be updated to provide RTL CSS if needed (we have pretty minimal CSS here, but I do see some right/left). Tracking that in #124.

**Comment by ryelle** [comment]
I think all the ongoing/future work related to i18n/rosetta is being tracked in #266, so I'm going to close this issue.
