### ISSUE TITLE
About page design and content tweaks

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-main-2022#188]
Alignment changes

![Screen Shot 2023-02-03 at 9 21 03 AM](https://user-images.githubusercontent.com/1017872/216441146-229b498a-84fc-4c98-8d96-28c887fe6dbe.jpg)

<img width="1712" alt="screen-shot-2023-02-09-at-14 39 25" src="https://user-images.githubusercontent.com/1017872/217989535-4c951ec8-d33d-42f9-a797-462ff95fb4a7.png">

**Comment by thetinyl** [comment]
@adamwoodnz Here are some copy updates for the main About page—let me know if you prefer screenshots for these in the future or if listing like this works well enough:

- **Our story section:** Remove spaces around the em dash (—) in the second paragraph = "The WordPress open source project has evolved in progressive ways over time—supported by skilled......"
- **Our mission section:** We say some form of "democratize/democratizing publishing" a lot on this page, hoping to be a little less repetitive with the following suggestion. Update copy at the end of the very last paragraph to read = "....and have dedicated countless hours to build a tool that offers anyone a voice." 
- **Four freedoms section**: Remove mention of 'Bill of Rights' from subcopy. Suggesting that it read as = "WordPress is licensed under the General Public License (GPLv2 or later) which provides four core freedoms:"
- **Four freedoms section:** Correct a small typo in the 4th freedom copy... Add an 's' to 'other' = "The freedom to distribute copies of your modified versions to others."

The following are suggestions for the subcopy of the link lists at the bottom of the page:

- **Under 'the details'**: Update to read = "Dive into the background details, like the GPL and other policies."
- **Under 'the people'**: Update to read = "Learn about the community, how we get along and show our pride."
- I think these should both fit the space without running onto a 3rd line, but please let me know if they are too long and throw the design off. 

I think @marko-srb will likely have further notes about the design of the subheadlines within the 'Our mission' section, but if they do show up more prominently as sub-heads, they shouldn't have punctuation. Since they all start with 'WordPress', capitalization is a bit of a non-issue since they have to be. 😄

**Comment by adamwoodnz** [comment]
Testimonials link to change to https://wordpress.org/news/category/community/, see https://github.com/WordPress/wporg-main-2022/issues/196

**Comment by adamwoodnz** [comment]
For other design fixes see comment https://github.com/WordPress/wporg-main-2022/issues/191#issuecomment-1415734830
