### ISSUE TITLE
Visual diff testing in the local environment

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-main-2022#2]
Is it feasible and worthwhile for us to implement a snapshot/visual diff regression test suite in the local environment using something like jest-image-snapshot?

The main use cases I can see are:
* Detecting external regressions (especially unexpected changes caused by Gutenberg updates)
* Detecting regressions across multiple pages (I fix a bug on Page A, it breaks something on Page B)

Note that this is a separate idea from detecting visual regressions in production as an ongoing monitoring process. We probably do need that, but that can come later.

Is this useful and important enough for it to be an early priority, or should we punt it?

**Comment by dd32** [comment]
For testing locally, https://github.com/garris/BackstopJS seems to work rather well on a mac.

Single-command, run it to generate a before image, make adjustments (code, or plugin updates) and it loads a browser page with screenshots at all the resolutions you've defined of the URLs you've defined, and offers a visual-diff of the changes.

**Comment by StevenDufresne** [comment]
For use case #1, I'm not certain if a local version would provide much value because of package lock files. As developers, we tend to not update packages frequently. We could manually keep track of 3rd party updates and updating plugins for regression-specific testing, but at that point, I think we might as well just manually update and run a sanity check.

For use case #2, I think it makes more sense for a codebase that is very shared, however, since our site is carved into multiple themes, I don't know that unintentional changes are a very big risk.

Thoughts?

**Comment by ryelle** [comment]
Core has some code for local regression testing with `jest-image-snapshot`: https://github.com/WordPress/wordpress-develop/tree/trunk/tests/visual-regression

Puppeteer can also take screenshots - I use this sometimes when reviewing core tickets, to take before & after screenshots. I end up writing custom scripts for each flow because I usually need to test something different each time, but the gist is:

- Manually check out `trunk`
- Script walks through a few pages, maybe trigger hover or focus states, and take screenshots (usually at 3 different screen sizes)
- Manually do work, or switch branches
- Run the same script to take the same screenshots
- Usually I stop here because I just want before/after, but they can also be diffed with [blink-diff](https://www.npmjs.com/package/blink-diff)

I like this approach because I can really control exactly what happens before the screenshot is taken.

This is an example of the diff output:
![dashboard-400](https://user-images.githubusercontent.com/541093/180035833-9c8874a9-ae0f-4aca-90ea-abcb21ac7a1b.png)

> Detecting external regressions

I agree with @StevenDufresne, I think this would be better detected by a production check. If I'm currently working on the site and have my plugins up to date, I'd probably notice something broken. If I'm not currently working on the site, I'm also not going to run the local test.

> Detecting regressions across multiple pages

IMO this is why we would use local visual testing — maybe for just the two pages it's not "worth it" yet, but as we roll out to more pages on w.org, I could see needing it.

I think `jest-image-snapshot` would be a good start, and we could probably build that into a github action, too. I don't think I would call this high-priority unless someone really wants to work on it, though.

**Comment by tellyworth** [comment]
This sounds promising, I agree though that it's probably not a high priority yet. It could wait till we have more in place and are thinking about rolling out more changes.

**Comment by tellyworth** [comment]
PS I could see a manually triggered script being useful generally on sandboxes: compare before and after updating a plugin or testing someone's patch for deploy.

**Comment by tellyworth** [comment]
#19 adds manually triggered backstopjs tests. Basically:

1. `yarn backstop:reference` to create snapshots
2. change something
3. `yarn backstop:test` to see what changed

**Comment by tellyworth** [comment]
I'll close this as done. If we decide to roll out some kind of CI workflow that can be a separate issue.
