### ISSUE TITLE
main.sh sync script is failing

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-main-2022#20]
**Describe the bug**
The bin/sync/main.sh script in the dotorg repo doesn't work.

It gets to the diff part, but doesn't display a diff. I haven't gone beyond that point because I don't want to commit something mangled.

I've probably done something dumb in copy-pasting the script but I'm not sure how to debug it. I took out the build part because the child theme has nothing to build.

**Comment by dd32** [comment]
Turned out that we were piping diffs through `less -RFS`, `-F` is `--quit-if-one-screen` which would skip displaying a diff if it fit on one screen.

Hadn't been run into because most diffs included JS/CSS changes, which never fit on a single screen.

It might've been needed for some purpose, @iandunn might know.

I fixed a few other small issues around the sync scripts while I was looking at it.

**Comment by iandunn** [comment]
🤔 I'm not sure. It looks like it existed since the initial commit, so there's no explicit message about it.

It should still display the diff, though, and just quit automatically _after_ the output has been printed. i.e., it should behave like `svn diff | cat` in that case, rather than not displaying it at all. I would think the `svn diff...` line in the script would still print to `STDOUT`, but maybe it would have had to be explicitly `echo`'d or something? BASH is fun 😆 

Removing `-F` seems like a good solution regardless 👍🏻
