### ISSUE TITLE
About Page: Consider breadcrumbs for The People, The Technology, The Details

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-main-2022#255]
The footer section of the about page has this section linking subpages, but with The People, The Technology, and The Details as _categories_:

<img width="1020" alt="Screenshot 2023-04-26 at 14 04 38" src="https://user-images.githubusercontent.com/1204802/234569477-46f9eb8f-ede4-450b-bbd7-9f681ab0f028.png">

_Let's by the way remove the north-east arrows from that module, both on the About page and anywhere else that uses these arrows. They have served to be decorative, but there has been confusion about the link (external/open in new tab) behavior related to that._

On subsections this makes wayfinding a bit harder, as the About subpages are still just direct ancestors to the About page itself. Shown here, Requirements, with no mention of "The Technology" categorization:

<img width="1392" alt="Screenshot 2023-04-26 at 14 07 15" src="https://user-images.githubusercontent.com/1204802/234569965-405e56eb-a097-4a0d-89f9-6be614a378b6.png">

This is made harder by the absence of a About page higlight in the dropdown:

<img width="1392" alt="Screenshot 2023-04-26 at 14 07 19" src="https://user-images.githubusercontent.com/1204802/234570019-51bc74a3-4ee2-404b-9a1d-450ae9445f1e.png">

This needs a quick design pass to figure out what we do here. CC: @panchovm @markoserb

**Comment by ryelle** [comment]
> This is made harder by the absence of a About page higlight in the dropdown:

Just noting that the section highlights were removed intentionally as reported in https://github.com/WordPress/wporg-mu-plugins/issues/370.

**Comment by jasmussen** [comment]
> Just noting that the section highlights were removed intentionally as reported in https://github.com/WordPress/wporg-mu-plugins/issues/370.

What I'm understanding technically here is that the top level `About ⌄` menu item is _the same_ page item as The About → [About WordPress] page item. They even lead to the same place. And so when removing the highlight for the top level, of course the highlight is removed from the same page item inside the dropdown.

But this is a problem with the top level dropdowns and how they are behaving as _categories_ doubling as links. This is what led to us discussing potentially changing those dropdowns to be click-only _categories_ rather than duplicate page links (related to [this conversation](https://github.com/WordPress/wporg-main-2022/issues/221#issuecomment-1523376929)).

The thing is, other dropdown items are highlighted when active, so it's currently awkward that "About WordPress" is not. 

Whether we fix this through an awkward hack that restores the active state but only for the item inside the dropdown, or whether we move forward to making the top level items open on click but not link anywhere themselves, both of those are related. Which is the better approach in your opinion? CC: @WordPress/meta-design

**Comment by fcoveram** [comment]
There are several points covered in this ticket, and since those are inherited from the header navigation, I will describe what I consider problems and possible solutions.

### Categories link to the category's first page

**Problem:** Clicking on a category that redirects to a page makes the navigation inconsistent. The link you click and the page you land on are not necessarily the same. "Community" redirects you to "Make”.

### Partial highlight mark

**Problem:** The highlight mark in the header disappears when you land on pages’ level 2 and beyond. When you go to “About WordPress”, the highlight is visible in the header. When you go to `about/features` page, the highlight is no longer visible. This makes the navigation inconsistent as the rule applied is not conveyed to users.

**Solution:** Show the highlight mark in pages, not in categories. Under that rule, “News" mark will be the only visible in the header's desktop version.

### Broken subnavegation

**Problem:** The nav component mixes sibling pages of the same category with the page's slug name, but it does not show a breadcrumb.

**Solution:** Show a breadcrumb with page names instead of slug, and list all pages at the same level.

## Header wireframe

The following wireframe covers the header and categories behavior.

<img width="1483" alt="Wireframes of header behavior in desktop and mobile views" src="https://user-images.githubusercontent.com/895819/234887539-3d835c15-21a9-4b82-bc44-eeb13d52bac5.png">

## About WordPress’ header

And for the “About” page, I think we can do the following

<img width="2259" alt="Wireframe of header in About WordPress page" src="https://user-images.githubusercontent.com/895819/234887589-15660a76-7611-458c-a339-fec9025df711.png">

For the subnavegation, and since level 2 pages are multiple, I reused the News component that lists the news categories. The image attached does not have visual definitions applied but points out the difference between category names and links.

Also notice that the previous "About" label is now a link named "About WordPress", like the page name.

---

What do you think of this idea?

**Comment by ryelle** [comment]
> What I’m understanding technically here is that the top level `About ⌄` menu item is *the same* page item as The About → [About WordPress] page item. And so when removing the highlight for the top level, of course the highlight is removed from the same page item inside the dropdown.
>
> The thing is, other dropdown items are highlighted when active, so it's currently awkward that "About WordPress" is not.

But we haven't removed the highlight for the top-level About page, it's still highlighted.

<img width="951" alt="Screenshot 2023-04-27 at 11 01 22 AM" src="https://user-images.githubusercontent.com/541093/234903969-d1f45cbe-a196-48e1-a8ec-84042b05eabe.png">

Just like the other top level pages:

<img width="968" alt="Screenshot 2023-04-27 at 11 01 49 AM" src="https://user-images.githubusercontent.com/541093/234904090-c208a8b8-9a82-4000-8623-86519c099f6b.png">

Once you get into subpages of About it's not highlighted anymore, but that's also how subpages of Download, Learn, make.w.org, etc work (now, thanks to https://github.com/WordPress/wporg-mu-plugins/issues/370).

**Comment by jasmussen** [comment]
> But we haven't removed the highlight for the top-level About page, it's still highlighted.

Oh, my mistake, sorry! Definitely speaks to Francisco's points.

**Comment by StevenDufresne** [comment]
> What do you think of this idea? @fcoveram 

I think this is well thought-out and a very logical structure. However, I do feel like we'll be giving preference to a number of links that are very underwhelming and unlikely to be clicked. I don't think that a prioritized journey into those pages benefits anyone. I feel like they are important, but only when needed and probably when specifically searched for, either landed directly from a google search result, or from our global search. 

In my estimation, I think the best approach is to flatten the about hierarchy and not design for deep or exploratory user paths. Pressing the back button or clicking the "Home" in the breadcrumb seems predictable and enough. The content should share the burden. If a user is looking for a quick way out in this context, I would surmise that our content has likely failed the user, not wayfinding.

I don't find these links compelling, even when they are contextualized under "the technology, the details, the people". 
| Links | 
| --- |
| <img width="478" alt="Screenshot 2023-05-02 at 1 20 35 PM" src="https://user-images.githubusercontent.com/1657336/235578523-133c8fd4-47dc-4237-8884-974227bf0047.png"> |

My vote would be to remove this secondary menu in the subnav and leave a breadcrumb on the path.

| Before | After |
| --- | --- |
|![wordpress org_about_etiquette_ (1)](https://user-images.githubusercontent.com/1657336/235579747-e91da9a1-f50f-47ad-bef8-64e855484d60.png) | <img src="https://user-images.githubusercontent.com/1657336/235579605-55106c72-5d86-4e42-86cc-530743b26ea6.png" /> |

If we want to provide a next step, maybe leverage the Next/Prev pagination concept that we have on the new developer designs and on news, since we are viewing in the context of grouped links.

| Developer|
| --- |
| <img width="1082" alt="Screenshot 2023-05-02 at 1 35 51 PM" src="https://user-images.githubusercontent.com/1657336/235580149-bdb7180d-ac4c-41b9-b756-cccb92170077.png"> |

**Comment by fcoveram** [comment]
>  I do feel like we'll be giving preference to a number of links that are very underwhelming and unlikely to be clicked. I don't think that a prioritized journey into those pages benefits anyone. I feel like they are important, but only when needed

I disagree with this statement. The [wireframe attached](https://user-images.githubusercontent.com/895819/234887539-3d835c15-21a9-4b82-bc44-eeb13d52bac5.png) is a site-wise component that covers how most current pages show links. What is considered important and needed varies per site section. Make's team blog is a good example of that.

Nonetheless, I plan to open a ticket diving into this idea and how it impacts the site.

> I think the best approach is to flatten the about hierarchy and not design for deep or exploratory user paths.

For this page, this approach sounds good to me. The current three-column area displaying all section's links (image attached below) works great for this purpose. So +1 to remove the right section of links and show all links in a component at the end of each page. In that vein, it would be great to highlight the active page to reinforce the existence of multiple pages and where you are.

<img width="900" alt="Links to About's subpages displayed in a three-column section" src="https://user-images.githubusercontent.com/895819/235631989-f195167a-7897-40c6-b83f-b25481c414ef.png">

**Comment by ryelle** [comment]
>  So +1 to remove the right section of links and show all links in a component at the end of each page.

Sounds good, and doesn't require any extra custom blocks :) If this is good to implement, just remove the two "design" labels.

**Comment by ryelle** [comment]
@jasmussen This is the issue I referenced on the call, and now I see you marked it as ready to implement. As I understand it, that would remove the top-right navigation and add the 3-col list at the end of the page, like this:

![Screen Shot 2023-05-03 at 12 44 23](https://user-images.githubusercontent.com/541093/235983873-f60a5bcc-aa79-4efb-8416-f1ce9dfa8070.png)

However, this design was shared by @marko-srb, adding in the news-style dropdown. This would require a bit more custom code, because we can't reuse the News component. That doesn't mean we can't do it — if this pattern will come up in multiple sections, we'll need to build it eventually. If it's only going to be used on About, maybe we should rethink whether the above solution would be better. 

<img width="1359" alt="Screenshot 2023-05-03 at 12 45 51 PM" src="https://user-images.githubusercontent.com/541093/235984116-b260c125-dfe3-40a3-8fcb-43fc8fc2a3cf.png">

In either case, I just want to have a clear idea of what to build before we do twice the work.

**Comment by jasmussen** [comment]
Thank you for connecting the dots 🙏

Let's let Marko get his About design to a place where he feels happy with it, then we'll take stock here and see what the next step can be. I think both can work, either the variant sketched out here with the table of categories in the footer, or the dropdown at the top, and it might be good to design both in this torn paper style, so we can see how they feel. I can dive in here as well if there's a lack of bandwidth, just let me know.

**Comment by ryelle** [comment]
Doing some housekeeping— I'm going to close this issue as we have since added the full local navigation to the About section, and and we've had more recent local navigation design discussions elsewhere.
