### ISSUE TITLE
Developers: Update padding on the Changelog box

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-main-2022#257]
This may be a content issue, but in case it's a more general issue, let me know. This box on the [First steps](https://wordpress.org/documentation/article/first-steps-with-wordpress-block-editor/) post, has a gray changelog box:

<img width="741" alt="Screenshot 2023-04-26 at 14 24 07" src="https://user-images.githubusercontent.com/1204802/234573875-61902f5d-9f17-41f7-8a3c-a6122e19cdf3.png">

I don't think we need a box there, to be honest. But if we do, it should be [one of the new grays](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=101%3A4031&t=7V3A1aeWAw7xOoNi-1):

<img width="869" alt="Screenshot 2023-04-26 at 14 25 53" src="https://user-images.githubusercontent.com/1204802/234574110-6824b676-503c-4a39-8655-0db6e1b9c7d4.png">

I'd pick the lightest of those.

In case it's a matter of the editor, it would be good to provide a theme palette with these colors, so the default Gutenberg grays aren't used.

**Comment by ryelle** [comment]
The [documentation site has its own repo](https://github.com/WordPress/wporg-documentation-2022/), and we already have an issue to create a changelog block & migrate these in-content changelogs: https://github.com/WordPress/wporg-documentation-2022/issues/6 (it was not considered a priority for launch, and with the redesign pause, the issue is a little stale now)

The changelogs on the site now are legacy content from the old documentation site, before the color palette existed. It's a custom color on a group block. The new colors are available in the editor:

<img width="320" alt="color palette" src="https://user-images.githubusercontent.com/541093/234610072-aaffbec5-a171-42c4-8f29-f89896b83f84.png">

**Comment by jasmussen** [comment]
Thanks for the clear response 🙏
