### ISSUE TITLE
Possible double strings

### ISSUE THREAD

**Issue by NekoJonez** [WordPress/wporg-main-2022#285]
While translating the newest strings for WP.org, I noticed that sometimes the cosistency tool was showing two strings... And I'm under the impression that we have some double strings...

These are two I found:

https://translate.wordpress.org/projects/meta/wordpress-org/nl-be/default/?filters[status]=either&filters[original_id]=5848165&filters[translation_id]=105619990
https://translate.wordpress.org/projects/meta/wordpress-org/nl-be/default/?filters[status]=either&filters[original_id]=16047146&filters[translation_id]=105619549

---

https://translate.wordpress.org/projects/meta/wordpress-org/nl-be/default/?filters[status]=either&filters[original_id]=5848112&filters[translation_id]=105619863
https://translate.wordpress.org/projects/meta/wordpress-org/nl-be/default/?filters[status]=either&filters[original_id]=16047117&filters[translation_id]=105619858

Could this be looked at, since now it has the chance that it destroys consistency. Or if they are different... Maybe add a translator note why they are different. Eg, one is a heading and the other is in text.

**Comment by tobifjellner** [comment]
GlotPress (and Gettext) use the source string as index key, so if there are several strings, then there is a difference between them.
In the strings you showed here, the source strings have different capitalization. 
Perhaps the American Camel Case is used for titles, and that could be useful to mention.

(And while we're at it, please don't try to recreate American Camel Case via CSS, because almost all our target languages handle this differently than US English.)

**Comment by ryelle** [comment]
Just to make it easier to compare, I pulled your examples out into a table here. The links go to the source code.

| Old theme content | New theme content |
|---|---|
| [Version Numbering and Security Releases](https://github.com/WordPress/wordpress.org/blob/e5286ae7851397cf07fceb9a34cdaf4443232c91/wordpress.org/public_html/wp-content/themes/pub/wporg-main/page-about-security.php#L125) | [Version numbering and security releases](https://github.com/WordPress/wporg-main-2022/blob/3a0135a254aa50f5614e605e69a380d29052b0cb/source/wp-content/themes/wporg-main-2022/patterns/about-security.php#L135) |
| <img width="638" alt="" src="https://github.com/WordPress/wporg-main-2022/assets/541093/f966f9d9-7917-4743-a92e-e21452b1da06"> | <img width="750" alt="" src="https://github.com/WordPress/wporg-main-2022/assets/541093/63b44504-a0c4-42ea-b5a9-39e7dc0171be"> |
| [WordPress.org Theme and Plugin Repositories](https://github.com/WordPress/wordpress.org/blob/e5286ae7851397cf07fceb9a34cdaf4443232c91/wordpress.org/public_html/wp-content/themes/pub/wporg-main/page-about-security.php#L336) | [WordPress.org theme and plugin repositories](https://github.com/WordPress/wporg-main-2022/blob/3a0135a254aa50f5614e605e69a380d29052b0cb/source/wp-content/themes/wporg-main-2022/patterns/about-security.php#L347) |
| <img width="648" alt="" src="https://github.com/WordPress/wporg-main-2022/assets/541093/d7319957-f8a7-4ea6-9163-459efa0871d1"> | <img width="723" alt="" src="https://github.com/WordPress/wporg-main-2022/assets/541093/6acb6432-9d03-431a-bccd-ce6956cd8ac5"> |

The first column is from the `wporg-main` theme, which is only used on the rosetta sites right now and will stop being used when the new theme is rolled out. The first column could be considered "deprecated."

I think the change to sentence case was an intentional style change by the marketing folks who worked on this, is that right @thetinyl @eidolonnight ?

**Comment by eidolonnight** [comment]
> the change to sentence case was an intentional style change by the marketing folks

Correct! The [WordPress Brand Writing Style Guide](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/) notes the following:

> Headlines and subheadlines are sentence case, without final punctuation.
Sentence case can help make headlines easier to read (or scan).

Just keep in mind that [there is an exception for News](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/#news-blog).

**Comment by StevenDufresne** [comment]
@NekoJonez Does that suffice? Is there anything left to action on this ticket.

**Comment by NekoJonez** [comment]
> @NekoJonez Does that suffice? Is there anything left to action on this ticket.

I would add comments where what is used. And also, Tobi's comment is important. In my locale, American Camel case is frowned upon

**Comment by ryelle** [comment]
We're not using CSS to force any capitalization, so that shouldn't be an issue.

> I would add comments where what is used.

The new strings should be the only ones used going forward. The old ones will still exist since the old `wporg-main` theme exists, but it will stop being used once the redesign is fully launched.

**Comment by NekoJonez** [comment]
I wanted to post a funny gif like "we are done here" but couldnt find one :P
Thanks everyone
(Since this is an issue that will solve itself through time)

**Comment by ryelle** [comment]
Thanks!
