### ISSUE TITLE
No comments in news?

### ISSUE THREAD

**Issue by javiercasares** [WordPress/wporg-main-2022#305]
I'm comparing in the ES version, 2 posts:

old: 
https://es.wordpress.org/2023/08/02/preocupacion-por-la-ley-de-ciberresiliencia-cra-de-la-union-europea/?new-theme=0

new:
https://es.wordpress.org/2023/08/02/preocupacion-por-la-ley-de-ciberresiliencia-cra-de-la-union-europea/?new-theme=1

And I cannot see the comments anywhere in the new version (I can see one comment in the old one). Are there yet?

**Comment by dd32** [comment]
This theme was never intended on being used for `/news/` and as such there exists no support for comments, yet. That probably needs to change for Rosetta, but, it's probably expected that the News theme would also be pushed out to Rosetta sites.

For some context:
 - For WordPress.org, `/news/` is a separate site from `/` and the theme has always been separate, latest iteration is: https://github.com/WordPress/wporg-news-2021
 - For Rosetta sites, `/` and `/news/` are the same site and currently they use the `wporg-main` theme for news (which WordPress.org never did). 
 - Rosetta is complicated in that since most locales don't have a `/news/` prefix on posts, it's probably not easy to roll out the new news theme there

**Comment by ryelle** [comment]
> Rosetta is complicated in that since most locales don't have a /news/ prefix on posts, it's probably not easy to roll out the new news theme there

Since the News theme was more of a living prototype, I think it makes more sense to add comment support to wporg-main-2022. Only the rosetta sites use posts, so it shouldn't affect anything on the main wordpress.org site.
