### ISSUE TITLE
Add redirect from `/sotw` to `/state-of-the-word`

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-main-2022#353]
The new State of the World landing page was recently launched. The official URL for the page is: https://wordpress.org/state-of-the-word/

That said, it would be great to implement a redirect from `wordpress.org/sotw` → `wordpress.org/state-of-the-word`. Some hashtags used to promote the event are #sotw and #sotw2023. It is also common for folks to use the acronym instead of typing out the entire phrase and the simplified URL would be easier to type.

**Comment by iandunn** [comment]
Done in https://meta.trac.wordpress.org/changeset/12972 👍🏻 

It's worth noting that we also have the `w.org` domain, and most requests there will redirect to `wordpress.org`. So folks can also type open https://w.org/sotw and it'll work. It'll be a little bit slower b/c it's 2 redirects rather than 1, but not really noticeable.
