### ISSUE TITLE
Adding Brushstroke Backgrounds to Home Page Design

### ISSUE THREAD

**Issue by ghost** [WordPress/wporg-main-2022#36]
Brushstroke shapes are an important part of the visual design of WordPress.org/News, why aren't those shapes used in the home page redesign?!

In my opinion, adding some of these design elements to the home page, in addition to making the design more beautiful, also helps to create a uniform design language across all sites.

Please see the attached screenshot
![screenshot](https://user-images.githubusercontent.com/4096027/182104353-83fb58e4-459a-4b8f-babd-1ec521c7d866.jpg)

**Comment by beafialho** [comment]
Thank you for your suggestion @Besyar.

The home and download page were thought out to be relatable with the News page, as seen in typography and colors, but to have their own simple and functional designs.

As more pages are eventually redesigned, we need to balance the usage of decorative elements and make pages land somewhere on the spectrum between more jazzy/expressive visuals and minimal/clean, depending on the content of each section so that they're appealing but not overwhelming to users.

An example being this section further down the page, for instance:
<img width="1686" alt="Captura de ecrã 2022-08-01, às 15 52 23" src="https://user-images.githubusercontent.com/65220155/182177690-8e8c4763-7a24-4b38-99a1-2ab3dbd45f0b.png">
