### ISSUE TITLE
Plugin Directory: Increase paragraph line height

### ISSUE THREAD

**Issue by beafialho** [WordPress/wporg-main-2022#413]
Currently, the line height of the Plugin Directory seems a bit too tight. I suggest increasing it and matching with the rest of the site for a more comfortable reading and browsing experience.

https://github.com/WordPress/wporg-main-2022/assets/65220155/38e47713-fe99-4d5c-bc0d-df267613c4c4

cc: @jasmussen

**Comment by ryelle** [comment]
This caught my eye because the parent theme should provide the right styles, but it looks like the plugin theme is still loading all the legacy styles.

It would probably be enough to remove `client/styles/base/_copy.scss`, but I tried a 🔥 🔥  approach getting rid of all of these that should be handled by the parent theme styles now.

```
D       client/styles/base
D       client/styles/base/_base.scss
D       client/styles/base/_copy.scss
D       client/styles/base/_tables.scss
D       client/styles/components/_captions.scss
D       client/styles/components/_components.scss
D       client/styles/components/_galleries.scss
D       client/styles/components/_media.scss
D       client/styles/generic
D       client/styles/generic/_generic.scss
D       client/styles/navigation
D       client/styles/navigation/_menus.scss
D       client/styles/navigation/_navigation.scss
D       client/styles/objects/_fields.scss
D       client/styles/objects/_objects.scss
D       client/styles/objects/_page_releases.scss
D       client/styles/settings/_colors.scss
D       client/styles/settings/_settings.scss
D       client/styles/settings/_typography.scss
D       client/styles/trumps
D       client/styles/trumps/_trumps.scss
```

The full patch is here: https://gist.github.com/ryelle/b98a41afc597ba64100e8fa9b728d398

@StevenDufresne @dd32 This is a pretty big change for not being involved much yet, so what do you think?

| Home | Single plugin |
|---|---|
| ![Screen Shot 2024-04-04 at 17 57 05-fullpage](https://github.com/WordPress/wporg-main-2022/assets/541093/68ef5731-10dc-48de-8770-4cbaa6141910) | ![Screen Shot 2024-04-04 at 17 57 28-fullpage](https://github.com/WordPress/wporg-main-2022/assets/541093/87937aea-6f63-41ac-8b1b-57c92244dd48) |

**Comment by StevenDufresne** [comment]
There aren't many hidden surprises with the plugin directory. I'm fine with this cleanup. Apply it. I'll run some tests on Monday before we send this back out for QA.

**Comment by ryelle** [comment]
Okay, I've done that in [this commit](https://meta.trac.wordpress.org/changeset/13466/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-plugins-2024). That fixes the line-height, as it's now correctly inheriting the style from the parent theme.
