### ISSUE TITLE
Performance: front-end

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-main-2022#45]
Let's put together a checklist of any front-end performance issues (current or potential) that need to be considered. We may not fix them all for initial launch, but the sooner we know about them the better.

- [x] Use webp for images
- [x] Load the download modal JS only on download page
- [x] Load the MU Latest Posts block JS in the footer
- [x] Largest Contentful Paint image was lazy loaded

**Comment by adamwoodnz** [comment]
[Desktop performance](https://pagespeed.web.dev/report?url=https%3A%2F%2Fwordpress.org%2Fmain-test%2F&form_factor=desktop) is acceptable probably, but there are 3 opportunities for improvements:

![Screen Shot 2022-08-08 at 12 26 23 PM](https://user-images.githubusercontent.com/1017872/183317396-b52104af-a5c9-47fb-b360-f2a21d4ee89c.jpg)

[Mobile performance](https://pagespeed.web.dev/report?url=https%3A%2F%2Fwordpress.org%2Fmain-test%2F&form_factor=mobile) is most likely unacceptable, mostly the same opportunities:

![Screen Shot 2022-08-08 at 12 29 22 PM](https://user-images.githubusercontent.com/1017872/183317508-8ef3e0d7-e2ea-4750-8fbd-3e1fb9b7e82a.jpg)

Image formatting and sizing, and optimisation of JS loading seem to be the key areas to focus on.

**Comment by adamwoodnz** [comment]
I've now replaced all the large images in the front page with `.webp` versions and that opportunity has been dismissed. The scores have dropped a little, but it seems the the JS issues have more impact.

**Comment by adamwoodnz** [comment]
[Download page desktop](https://pagespeed.web.dev/report?url=https%3A%2F%2Fwordpress.org%2Fmain-test%2Fdownload&form_factor=desktop) score is excellent. [Mobile](https://pagespeed.web.dev/report?url=https%3A%2F%2Fwordpress.org%2Fmain-test%2Fdownload&form_factor=mobile) shows similar issues to front page:

![Screen Shot 2022-08-08 at 2 12 54 PM](https://user-images.githubusercontent.com/1017872/183324922-a7056fd0-1614-4032-9990-2d318b87f935.jpg)

**Comment by adamwoodnz** [comment]
Gutenberg issue raised related to JS loading: https://github.com/WordPress/gutenberg/issues/43054

**Comment by ryelle** [comment]
@adamwoodnz or @renintw  Can you put together a checklist of any items that still need to be done?

**Comment by adamwoodnz** [comment]
Lighthouse scores are very good now, only Download page on mobile is below 90:

| Desktop | Mobile |
|--------|--------|
| ![Screen Shot 2022-08-10 at 9 30 28 AM](https://user-images.githubusercontent.com/1017872/183766129-67ab88c1-c703-488e-8e47-c0416d9c2b3f.jpg) | ![Screen Shot 2022-08-10 at 9 31 57 AM](https://user-images.githubusercontent.com/1017872/183766168-dad21830-f66b-45e2-bdc9-c6304a72c5ef.jpg) |
| ![Screen Shot 2022-08-10 at 9 35 29 AM](https://user-images.githubusercontent.com/1017872/183766296-9d503bbe-79e9-41ee-8833-01de16e3b6a1.jpg) | ![Screen Shot 2022-08-10 at 9 34 54 AM](https://user-images.githubusercontent.com/1017872/183766375-502f2a2f-5556-4bc1-97b9-932660c09cc7.jpg) |

The download page mobile score is largely due to the `wordpress/components` import which we have Gutenberg issues for already but needs further discussion after launch.

The remaining opportunities/issues are:
1. Reduce server response time
![Screen Shot 2022-08-10 at 9 43 22 AM](https://user-images.githubusercontent.com/1017872/183767103-c312668e-9680-4d65-8520-f40d60136aaa.jpg)
2. Eliminate render blocking resources - mostly related to the latest posts block imports
![Screen Shot 2022-08-10 at 9 44 45 AM](https://user-images.githubusercontent.com/1017872/183767385-861ac90e-913f-41ef-9d3c-88575eb2b274.jpg)
3. Largest Contentful Paint image was lazy loaded - the cover image for 'Dream it, build it' section is lazy loaded
![Screen Shot 2022-08-10 at 9 46 47 AM](https://user-images.githubusercontent.com/1017872/183767608-f87203ae-e3c9-464c-a7eb-ffc3e545339c.jpg)

Of these I think 2 is the most important. We could look at a webpack tree shaking solution to reduce the size of the import, but also not loading the scripts in `head` would make a big difference.

**Comment by ryelle** [comment]
The homepage should stop loading `lodash` once GB 13.9 comes out, it looks like `wp-element` is the only dependant, and the lodash dep has been removed last week (https://github.com/WordPress/gutenberg/pull/42898).

I just made a quick PR to move the latest posts code into the footer: https://github.com/WordPress/wporg-mu-plugins/pull/245 — I'm not sure how much that helps in reality, since some of the deps are still loaded in the header.

**Comment by adamwoodnz** [comment]
> I'm not sure how much that helps in reality, since some of the deps are still loaded in the header.

Just loading that up now to see how much effect it has. There is a ticket for enqueuing block scripts in the footer https://core.trac.wordpress.org/ticket/54018

**Comment by adamwoodnz** [comment]
> 2. Eliminate render blocking resources - mostly related to the latest posts block imports

Merged https://github.com/WordPress/wporg-mu-plugins/pull/245 so this is largely mitigated. `react-dom` is still loaded in the `head` and flagged as render blocking. There are other smaller GB scripts which don't get flagged.

**Comment by ryelle** [comment]
> 1. Reduce server response time

That would be tracked in #44 

> 3. Largest Contentful Paint image was lazy loaded - the cover image for 'Dream it, build it' section is lazy loaded

Could look into how core adds these attributes, I found a dev note about [skipping X images from being lazy-loaded](https://make.wordpress.org/core/2021/12/29/enhanced-lazy-loading-performance-in-5-9/). That could be the answer or it could point us in the right direction.
