### ISSUE TITLE
Adding utm params to WPCOM Links on Dotorg Hosting Page

### ISSUE THREAD

**Issue by sethmclellana8c** [WordPress/wporg-main-2022#470]
Can you please update the two WordPress.com links on the [Dotorg Hosting page](https://href.li/?https://wordpress.org/hosting/) to include utm params (see links below)? The other hosts on the page have utm trackers, so I assume there won’t be a problem including utms.

**Free link (in initial paragraph)**
<img width="1300" alt="image" src="https://github.com/user-attachments/assets/42015710-b113-438d-9eff-48026e5b8036">

Before

`https://wordpress.com/wordpress-free/`

AFTER

`https://wordpress.com/wordpress-free/?utm_source=wporg&utm_medium=referral&utm_campaign=hosting_page_free`

**Paid link (Linked WordPress.com title in our section)**

<img width="1188" alt="image" src="https://github.com/user-attachments/assets/8fa54d88-f7a2-4a83-8b1b-cb8863e25083">

Before

`https://wordpress.com/wordpress-hosting/`

AFTER

`https://wordpress.com/wordpress-hosting/?utm_source=wporg&utm_medium=referral&utm_campaign=hosting_page_paid`

Thanks.

**Comment by sethmclellana8c** [comment]
@dansoschin

**Comment by dd32** [comment]
Hey @sethmclellana8c!

I think I'd prefer not to add this, as I'm not sure WordPress.org should be setting campaign-tracking-related parameters for 3rd parties.

The other hosts listed on that page don't have them included in the provided links either, and in a way this is cleaner as the links are then sharable too.

However, the other hosts do have campaign-tracking-related links in that the links that we've got redirect to their specials and/or add affiliate or UTM parameters.

In the interest of ensuring that all hosts on the page are treated equally, and to provide most flexibility to WordPress.com as the other hosts have, do you think it'd be possible for WordPress.com to do something similar to the other hosts? Have a dedicated link that y'all can set to redirect with UTM params or to a wporg-specific special, etc?

That would also reduce the likelihood of future requests to change the parameters if WordPress.com analytics changes in some manner.

Not closing this yet, but if that looks like an option, let us know what the new url on wpcom is for that, otherwise I guess we can just do this for you, given the tracking the others implement.

**Comment by sethmclellana8c** [comment]
Ah, good call. I was looking at the final resolved url.

Let me ask my team what they can do and I'll get back to you. Thanks.

Noting:

**Bluehost**
Actual link: `https://www.bluehost.com/wordpress-hosting`
Final resolved: `https://www.bluehost.com/special/wordpress?utm_campaign=wordpressorg&utm_source=wordpressorg&utm_medium=referral&channelID=P61C46097236S625N0B2A151D0E0000V100`

**Hostinger**
Actual link: `https://www.hostinger.com/special/wordpress`
Final resolved: `https://www.hostinger.com/wordpress?utm_source=aff177698&utm_campaign=768&session=102a5a294493fc0e2d3cf5cb9ad3fe`

**DreamHost**
Actual link: `https://www.dreamhost.com/wordpress-hosting/`
Final resolved: `https://www.dreamhost.com/wordpress/?`

**Comment by dd32** [comment]
Additionally some of those URLs also redirect multiple times through their
affiliate platform for tracking.

**Comment by sethmclellana8c** [comment]
@dd32 Thanks for your patience. I talked with our internal team and we'll setup a redirect with them. Appreciate the consideration. This request can be closed.
